services:
  task.api:
    image: task.api
    build:
      context: .
      dockerfile: src/Task.API/Dockerfile
      args:
        - DEV_CERT_PASSWORD=${DEV_CERT_PASSWORD}
    env_file:
      - .env
    networks:
      my-tasks:
    ports:
      - 7020:7020
      - 7021:7021
  
  task.database:
    image: postgres:16-alpine
      
networks:
  my-tasks:
