services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      my-tasks:
    restart: unless-stopped
    
  task.api:
    image: task.api
    build:
      context: .
      dockerfile: src/Task.API/Dockerfile
      args:
        - DEV_CERT_PASSWORD=${DEV_CERT_PASSWORD}
    env_file:
      - .env
    depends_on:
      - task.database
    networks:
      my-tasks:
    ports:
      - "7020:7020"
      - "7021:7021"
  
  task.database:
    image: postgres:16-alpine
    container_name: task.database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - task_postgres:/data/postgres
    ports:
      - "54321:5432"
    networks:
      my-tasks:
    restart: unless-stopped
    
volumes:
  task_postgres:
  pgadmin:
      
networks:
  my-tasks:
    driver: bridge
